name       : mono-msbuild
version    : 15.6
release    : 1
source     :
    - https://github.com/mono/linux-packaging-msbuild/archive/debian/1%2515.6+xamarinxplat.2018.01.17.14.14-0xamarin2.tar.gz : 6ef768a0b104e82407996e018eda91cbb4ed69d7fae81577eecec9a7d792f703
    - http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7ubuntu0.4_amd64.deb : 8774f8b2cad6a53deada1c80164e8ba1ac8e674ed02cd196f1548caf91c6f437
    - http://de.archive.ubuntu.com/ubuntu/pool/main/l/llvm-toolchain-3.6/liblldb-3.6_3.6.2-3ubuntu2_amd64.deb : 85f0f657e204f09a96885f5ecc9ae843c6de3aa8774611289ce7c4c117f59326
license    : MIT
component  : programming.tools
summary    : the build platform for .NET and Visual Studio
description: |
    The Microsoft Build Engine is a platform for building applications. This engine, which is also known as MSBuild, provides an XML schema for a project file that controls how the build platform processes and builds software.
networking : yes
builddeps  :
    - pkgconfig(mono)
    - liblttng-ust
    - libunwind
rundeps    :
    - mono
setup      : |
    temp_dir=/tmp/ubuntu
    mkdir $temp_dir
    pushd $temp_dir
    for file in $sources/*.deb; do
        ar x $file
        tar -xf data.tar.xz
    done
    popd
    mkdir ubuntu_libs
    mv $temp_dir/usr/lib/x86_64-linux-gnu/* ubuntu_libs/
    patch -p1 < $pkgfiles/0001-Force-Ubuntu-version.patch
    patch -p1 < $pkgfiles/0002-Force-verbosity-to-diagnostic.patch
build      : |
    export LD_LIBRARY_PATH="$PWD/ubuntu_libs:$LD_LIBRARY_PATH"
    export __PUBLISH_RID=ubuntu.16.04-x64
    ./cibuild.sh --scope Compile --host Mono --target Mono --config Release
install    : |
    ./install-mono-prefix.sh $installdir/usr
    sed -i -e 's#/home/build/YPKG/root/mono-msbuild/install##g' $installdir/usr/bin/msbuild
