name       : mono-msbuild
version    : '16.8'
release    : 6
source     :
    - https://github.com/mono/linux-packaging-msbuild/archive/upstream/16.8+xamarinxplat.2020.07.30.15.02.tar.gz : 418fd785988347d9e78f634fd62440b65be3115582f85b6f91d9d7893178b579
    - https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.100/dotnet-sdk-3.1.100-linux-x64.tar.gz : 3687b2a150cd5fef6d60a4693b4166994f32499c507cd04f346b6dda38ecdc46
license    : MIT
component  : programming.tools
summary    :
    - The build platform for .NET and Visual Studio
description: |
    The Microsoft Build Engine is a platform for building applications. This engine, which is also known as MSBuild, provides an XML schema for a project file that controls how the build platform processes and builds software.
networking : yes
builddeps  :
    - pkgconfig(mono)
    - mono-msbuild
rundeps    :
    - mono
environment: |
    export LD_LIBRARY_PATH=$(dirname $workdir/.dotnet/host/fxr/*/libhostfxr.so):$LD_LIBRARY_PATH
setup      : |
    cert-sync --user /etc/ssl/certs/ca-certificates.crt
    mkdir .dotnet
    tar xf $sources/dotnet-sdk* --strip-components=1 -C .dotnet
    cp $pkgfiles/NuGet.config .
    mv LICENSE license
build      : |
    ./eng/cibuild_bootstrapped_msbuild.sh --host_type mono --configuration Release --binaryLog --skip_tests /p:DotNetBuildFromSource=true
install    : |
    sed -i -e "s|4</WarningLevel>|3</WarningLevel>|" artifacts/bin/MSBuild.Bootstrap/Release-MONO/net472/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.CSharp.props
    msbuild mono/build/install.proj /p:MonoInstallPrefix="$installdir/usr" /p:Configuration=Release-MONO /p:IgnoreDiffFailure=true
    sed -i -e "s|$installdir||g" $installdir/usr/bin/msbuild
