name       : mono-msbuild
version    : '16.3'
release    : 3
source     :
    - https://github.com/mono/linux-packaging-msbuild/archive/upstream/16.3+xamarinxplat.2019.08.08.00.55.tar.gz : ec3589672cf2c68f2d32240d843974bd905a9973916ce53b82e136566befbfb9
license    : MIT
component  : programming.tools
summary    : the build platform for .NET and Visual Studio
description: |
    The Microsoft Build Engine is a platform for building applications. This engine, which is also known as MSBuild, provides an XML schema for a project file that controls how the build platform processes and builds software.
networking : yes
builddeps  :
    - pkgconfig(mono)
    - libunwind
    - mono-msbuild
rundeps    :
    - mono
setup      : |
    cert-sync --user /etc/ssl/certs/ca-certificates.crt
    %patch -p1 < $pkgfiles/Remove-Microsoft.DotNet.MSBuildSdkResolver.patch
    mv LICENSE license
build      : |
    %make all-mono
install    : |
    ./install-mono-prefix.sh $installdir/usr
    sed -i -e "s|$installdir||g" $installdir/usr/bin/msbuild
