name       : mono-msbuild
version    : '16.5'
release    : 5
source     :
    - https://github.com/mono/linux-packaging-msbuild/archive/upstream/16.5+xamarinxplat.2020.01.10.05.36.tar.gz : 5062f73e0425dcd68c9d5cb088583d18d1ec8936edc41527731acd9a243d0c13
license    : MIT
component  : programming.tools
summary    : the build platform for .NET and Visual Studio
description: |
    The Microsoft Build Engine is a platform for building applications. This engine, which is also known as MSBuild, provides an XML schema for a project file that controls how the build platform processes and builds software.
networking : yes
builddeps  :
    - pkgconfig(mono)
    - mono-msbuild
rundeps    :
    - mono
setup      : |
    cert-sync --user /etc/ssl/certs/ca-certificates.crt
    %patch -p1 < $pkgfiles/Remove-Microsoft.DotNet.MSBuildSdkResolver.patch
    %patch -p1 < $pkgfiles/Correct-DotNetBitsVersions.props.patch
    mv LICENSE license
build      : |
    %make all-mono
install    : |
    ./install-mono-prefix.sh $installdir/usr
    sed -i -e "s|$installdir||g" $installdir/usr/bin/msbuild
    rm -rf $installdir/usr/lib/mono/xbuild/15.0
